### ISSUE TITLE
Trained model

### ISSUE THREAD

**Issue by javadmozaffari** [caizexin/speechbrain_PartialFake#1]
Hello,

I would like to thank you for your excellent work. I was wondering if you could provide the trained weight of your model for Inference part?

**Comment by caizexin** [comment]
Sure. However, I have removed the original trained models due to their large size, which made them impractical to upload directly on GitHub. Please allow me 2 to 3 days to retrain the model and upload them to Google Drive. Once this is complete, I will let you know and update the repository’s README file with the relevant download links and instructions.

**Comment by caizexin** [comment]
Please access the trained models from [Google Drive](https://drive.google.com/file/d/1Ung_DQMikwBmFxokmSrPq7lSnohctRNm/view?usp=sharing) and place it in the "_ADD_2023/results/1994/wav2vec_melnet_bdr/1.28/add_train/save_" directory.
